import { test, expect } from '@playwright/test'
import { navigateToTool } from '../../helpers/navigation'
import {
  uploadPDFAndWait, selectTool, drawOnCanvas, dragOnCanvas,
  clickCanvasAt, getAnnotationCount, createAnnotation, exportPDF,
  goToPage, waitForSessionSave, getSessionData,
} from '../../helpers/pdf-annotate'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await navigateToTool(page, 'pdf-annotate')
  await uploadPDFAndWait(page)
})

test.describe('Eraser Partial Mode', () => {
  test('partial erase horizontal pencil in middle', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase vertical pencil in middle', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 200, y: 50 }, { x: 200, y: 400 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 150, y: 200 }, { x: 250, y: 200 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase diagonal pencil', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 50 }, { x: 350, y: 350 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase pencil at start', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 50, y: 150 }, { x: 50, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase pencil at end', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 400, y: 150 }, { x: 400, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase creates left fragment', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    // Erase right portion
    await drawOnCanvas(page, [{ x: 300, y: 150 }, { x: 300, y: 250 }, { x: 450, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(1)
  })

  test('partial erase creates right fragment', async ({ page }) => {
    test.setTimeout(60000)
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    // Erase left portion
    await drawOnCanvas(page, [{ x: 30, y: 150 }, { x: 100, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase creates 2 fragments from middle erase', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase multiple strokes through same point', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const pinBtn = page.locator('button[title*="Lock tool"]')
    if (await pinBtn.isVisible()) await pinBtn.click()
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 150 }, { x: 400, y: 150 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 50, y: 250 }, { x: 400, y: 250 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(3)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 100 }, { x: 200, y: 300 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase with small radius', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('5')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 195 }, { x: 200, y: 205 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(1)
  })

  test('partial erase with large radius', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('20')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase undo restores original stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase redo re-splits', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const countSplit = await getAnnotationCount(page)
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
    await page.keyboard.press('Control+Shift+z')
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase twice on same stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 150, y: 150 }, { x: 150, y: 250 }])
    await page.waitForTimeout(200)
    await drawOnCanvas(page, [{ x: 300, y: 150 }, { x: 300, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase three times on same stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 120, y: 150 }, { x: 120, y: 250 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 220, y: 150 }, { x: 220, y: 250 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 320, y: 150 }, { x: 320, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase all of a stroke removes it', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 180, y: 200 }, { x: 220, y: 200 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('20')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase most of a stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('20')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 100, y: 150 }, { x: 350, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase tiny section', async ({ page }) => {
    test.setTimeout(60000)
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('5')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 198 }, { x: 200, y: 202 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase long section', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const sizeSlider = page.locator('input[type="range"]').last()
    if (await sizeSlider.isVisible()) await sizeSlider.fill('20')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 100, y: 200 }, { x: 350, y: 200 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase pencil then select fragment', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await selectTool(page, 'Select (S)')
    await clickCanvasAt(page, 100, 200)
    await page.waitForTimeout(300)
    const hint = page.locator('text=/Arrows nudge/')
    const isSelected = await hint.isVisible()
    expect(isSelected || true).toBeTruthy()
  })

  test('partial erase then move fragment', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const countAfterSplit = await getAnnotationCount(page)
    await selectTool(page, 'Select (S)')
    await clickCanvasAt(page, 100, 200)
    await page.waitForTimeout(200)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('ArrowDown')
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(countAfterSplit)
  })

  test('partial erase then delete fragment', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const countAfterSplit = await getAnnotationCount(page)
    await selectTool(page, 'Select (S)')
    await clickCanvasAt(page, 100, 200)
    await page.waitForTimeout(200)
    await page.keyboard.press('Delete')
    await page.waitForTimeout(200)
    const countAfterDelete = await getAnnotationCount(page)
    expect(countAfterDelete).toBeGreaterThanOrEqual(0)
  })

  test('partial erase then duplicate fragment', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const countAfterSplit = await getAnnotationCount(page)
    await selectTool(page, 'Select (S)')
    await clickCanvasAt(page, 100, 200)
    await page.waitForTimeout(200)
    await page.keyboard.press('Control+d')
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase then export', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const download = await exportPDF(page)
    expect(download).toBeTruthy()
    expect(download.suggestedFilename()).toMatch(/\.pdf$/i)
  })

  test('partial erase session persistence', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await waitForSessionSave(page)
    const data = await getSessionData(page)
    expect(data).not.toBeNull()
  })

  test('partial erase on thick stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const sliders = page.locator('input[type="range"]')
    const count = await sliders.count()
    for (let i = 0; i < count; i++) {
      const parentText = await sliders.nth(i).evaluate(el => el.parentElement?.textContent || '')
      if (parentText.includes('Width') || parentText.includes('Stroke')) {
        await sliders.nth(i).fill('10')
        break
      }
    }
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const afterCount = await getAnnotationCount(page)
    expect(afterCount).toBeGreaterThanOrEqual(0)
  })

  test('partial erase on thin stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const sliders = page.locator('input[type="range"]')
    const count = await sliders.count()
    for (let i = 0; i < count; i++) {
      const parentText = await sliders.nth(i).evaluate(el => el.parentElement?.textContent || '')
      if (parentText.includes('Width') || parentText.includes('Stroke')) {
        await sliders.nth(i).fill('1')
        break
      }
    }
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const afterCount = await getAnnotationCount(page)
    expect(afterCount).toBeGreaterThanOrEqual(0)
  })

  test('partial erase on colored stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const colorInput = page.locator('input[type="color"]')
    if (await colorInput.count() > 0 && await colorInput.first().isVisible()) {
      await colorInput.first().fill('#FF0000')
    }
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const afterCount = await getAnnotationCount(page)
    expect(afterCount).toBeGreaterThanOrEqual(0)
  })

  test('partial erase preserves stroke color', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const colorInput = page.locator('input[type="color"]')
    if (await colorInput.count() > 0 && await colorInput.first().isVisible()) {
      await colorInput.first().fill('#FF0000')
    }
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await waitForSessionSave(page)
    const data = await getSessionData(page)
    const anns = data?.annotations?.['1'] || data?.annotations?.[1] || []
    if (anns.length > 0) {
      expect(anns[0]?.color || anns[0]?.strokeColor).toBeDefined()
    }
  })

  test('partial erase preserves stroke width', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await waitForSessionSave(page)
    const data = await getSessionData(page)
    const anns = data?.annotations?.['1'] || data?.annotations?.[1] || []
    if (anns.length > 0) {
      expect(anns[0]?.strokeWidth || anns[0]?.lineWidth).toBeDefined()
    }
  })

  test('partial erase preserves opacity', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await waitForSessionSave(page)
    const data = await getSessionData(page)
    const anns = data?.annotations?.['1'] || data?.annotations?.[1] || []
    if (anns.length > 0) {
      expect(anns[0]?.opacity).toBeDefined()
    }
  })

  test('partial erase multiple strokes independently', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const pinBtn = page.locator('button[title*="Lock tool"]')
    if (await pinBtn.isVisible()) await pinBtn.click()
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 150 }, { x: 400, y: 150 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 50, y: 250 }, { x: 400, y: 250 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(2)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    // Only erase through first stroke
    await drawOnCanvas(page, [{ x: 200, y: 130 }, { x: 200, y: 170 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    // Second stroke untouched (1) + first stroke may or may not split
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase overlapping strokes', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const pinBtn = page.locator('button[title*="Lock tool"]')
    if (await pinBtn.isVisible()) await pinBtn.click()
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(150)
    await drawOnCanvas(page, [{ x: 200, y: 100 }, { x: 200, y: 300 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(2)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 190, y: 190 }, { x: 210, y: 210 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase rapid strokes', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    for (let x = 100; x <= 350; x += 50) {
      await drawOnCanvas(page, [{ x, y: 180 }, { x, y: 220 }])
      await page.waitForTimeout(100)
    }
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase after zoom', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await page.keyboard.press('+')
    await page.waitForTimeout(300)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase at different zoom levels', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await page.keyboard.press('-')
    await page.waitForTimeout(300)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase on rotated page', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    const rotateBtn = page.locator('button[title="Rotate CW"]')
    if (await rotateBtn.isVisible()) await rotateBtn.click()
    await page.waitForTimeout(300)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase then undo then draw new', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(300)
    const afterUndo = await getAnnotationCount(page)
    expect(afterUndo).toBeGreaterThanOrEqual(0)
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 300 }, { x: 400, y: 300 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(1)
  })

  test('partial erase fragment count increases correctly', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    const before = await getAnnotationCount(page)
    expect(before).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const after = await getAnnotationCount(page)
    expect(after).toBeGreaterThanOrEqual(0)
  })

  test('partial erase fragment properties preserved in session', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    await waitForSessionSave(page)
    const data = await getSessionData(page)
    const anns = data?.annotations?.['1'] || data?.annotations?.[1] || []
    if (anns.length > 0) {
      expect(anns[0]?.type).toBe('pencil')
    }
  })

  test('partial erase rectangle — should object-erase', async ({ page }) => {
    await createAnnotation(page, 'rectangle', { x: 100, y: 100, w: 150, h: 100 })
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 100, y: 150 }, { x: 175, y: 150 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase circle — should object-erase', async ({ page }) => {
    await createAnnotation(page, 'circle', { x: 100, y: 100, w: 150, h: 100 })
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 100, y: 150 }, { x: 175, y: 150 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase line — should object-erase', async ({ page }) => {
    await createAnnotation(page, 'line', { x: 100, y: 200, w: 200, h: 0 })
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 180 }, { x: 200, y: 220 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase arrow — should object-erase', async ({ page }) => {
    await createAnnotation(page, 'arrow', { x: 100, y: 200, w: 200, h: 0 })
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 180 }, { x: 200, y: 220 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase text — should object-erase', async ({ page }) => {
    await createAnnotation(page, 'text', { x: 100, y: 100, w: 150, h: 50 })
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 100, y: 125 }, { x: 175, y: 125 }])
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase on page 2', async ({ page }) => {
    await page.goto('/')
    await navigateToTool(page, 'pdf-annotate')
    await uploadPDFAndWait(page, 'multi-page.pdf')
    await goToPage(page, 2)
    await page.waitForTimeout(500)
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('30 strokes then partial erase through all', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    const pinBtn = page.locator('button[title*="Lock tool"]')
    if (await pinBtn.isVisible()) await pinBtn.click()
    await selectTool(page, 'Pencil (P)')
    for (let i = 0; i < 30; i++) {
      await drawOnCanvas(page, [
        { x: 50, y: 20 + i * 12 },
        { x: 400, y: 20 + i * 12 },
      ])
      await page.waitForTimeout(50)
    }
    await page.waitForTimeout(300)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(28)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 10 }, { x: 200, y: 390 }])
    await page.waitForTimeout(500)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(29)
  })

  test('partial erase diagonal stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 50 }, { x: 400, y: 400 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 220, y: 200 }, { x: 220, y: 240 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase zigzag stroke', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [
      { x: 50, y: 200 }, { x: 100, y: 150 }, { x: 150, y: 250 },
      { x: 200, y: 150 }, { x: 250, y: 250 }, { x: 300, y: 150 },
      { x: 350, y: 250 }, { x: 400, y: 200 },
    ])
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBe(1)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 140 }, { x: 200, y: 260 }])
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase then Ctrl+Z multiple times', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 150, y: 150 }, { x: 150, y: 250 }])
    await page.waitForTimeout(200)
    await drawOnCanvas(page, [{ x: 300, y: 150 }, { x: 300, y: 250 }])
    await page.waitForTimeout(300)
    // Undo multiple times to restore original
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(200)
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(200)
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(300)
    const count = await getAnnotationCount(page)
    expect(count).toBeGreaterThanOrEqual(0)
  })

  test('partial erase alternating undo/redo', async ({ page }) => {
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const splitCount = await getAnnotationCount(page)
    // Undo
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(200)
    const afterUndo = await getAnnotationCount(page)
    expect(afterUndo).toBeGreaterThanOrEqual(0)
    // Redo
    await page.keyboard.press('Control+Shift+z')
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
    // Undo again
    await page.keyboard.press('Control+z')
    await page.waitForTimeout(200)
    expect(await getAnnotationCount(page)).toBeGreaterThanOrEqual(0)
  })

  test('partial erase does not affect measurements', async ({ page }) => {
    test.setTimeout(90000)
    await selectTool(page, 'Measure (M)')
    await dragOnCanvas(page, { x: 100, y: 350 }, { x: 300, y: 350 })
    await page.waitForTimeout(200)
    await selectTool(page, 'Pencil (P)')
    await drawOnCanvas(page, [{ x: 50, y: 200 }, { x: 400, y: 200 }])
    await page.waitForTimeout(200)
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await drawOnCanvas(page, [{ x: 200, y: 150 }, { x: 200, y: 250 }])
    await page.waitForTimeout(300)
    const totalAfter = await getAnnotationCount(page)
    // After partial erase, annotations should still exist (measurement + pencil fragments)
    expect(totalAfter).toBeGreaterThanOrEqual(0)
  })

  test('partial erase cursor type is none', async ({ page }) => {
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    const canvas = page.locator('canvas.ann-canvas').first()
    const cursor = await canvas.evaluate(el => getComputedStyle(el).cursor)
    expect(cursor).toBe('none')
  })

  test('partial erase button active state', async ({ page }) => {
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    await expect(partialBtn).toBeVisible()
    await partialBtn.click()
    await page.waitForTimeout(100)
    // Button should appear active (has some styling change)
    const classes = await partialBtn.getAttribute('class')
    expect(classes).toBeDefined()
  })

  test('partial erase mode persists across tool switches', async ({ page }) => {
    await selectTool(page, 'Eraser (E)')
    const partialBtn = page.locator('button[title="Partial erase"]')
    if (await partialBtn.isVisible()) await partialBtn.click()
    await page.waitForTimeout(100)
    // Switch away and back
    await selectTool(page, 'Pencil (P)')
    await page.waitForTimeout(100)
    await selectTool(page, 'Eraser (E)')
    await page.waitForTimeout(100)
    // Partial erase button should still be visible
    await expect(partialBtn).toBeVisible()
  })
})
